name: "Continuous Integration"

on:
  pull_request: null
  push:
    branches:
      - "*.x"
      - "master"
  schedule:
    - cron: "42 3 * * 1"

jobs:
  phpunit-mysql:
    name: ${{ matrix.job }}${{ matrix.name }} (PHP ${{ matrix.php-version }} / MySQL ${{ matrix.mysql-version }})
    runs-on: "ubuntu-24.04"
    strategy:
      matrix:
        php-version:
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
        mysql-version:
          - "8.0"
        dependencies:
          - "highest"
        composer-options: 
          - "--prefer-dist"
        job:
          - Tests
        include:
          - php-version: "8.5"
            mysql-version: "8.4"
          - php-version: "8.5"
            mysql-version: "8.2"
            job: Infection
          - dependencies: "lowest"
            php-version: "8.1"
            mysql-version: "5.7"
            name: Lowest deps

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v6"
        with:
          fetch-depth: 2

      - name: "Fix Git permissions"
        run: 'git config --global --add safe.directory /app'

      - name: "Remove Psalm & Infection deps"
        run: 'make composer-remove-psalm'
        if: matrix.job != 'Infection'
        env:
          PHP_VERSION: "${{ matrix.php-version }}"
        
      - name: "Setup project"
        run: 'make setup'
        env:
          MYSQL_VERSION: "${{ matrix.mysql-version }}"
          PHP_VERSION: "${{ matrix.php-version }}"

      - name: "Run PHPUnit with coverage"
        run: "make test-with-coverage"
        if: matrix.job != 'Infection'
        env:
          MYSQL_VERSION: "${{ matrix.mysql-version }}"
          PHP_VERSION: "${{ matrix.php-version }}"

      - name: "Run mutation testing with Infection"
        run: "make infection"
        if: matrix.job == 'Infection'
        env:
          MYSQL_VERSION: "${{ matrix.mysql-version }}"
          PHP_VERSION: "${{ matrix.php-version }}"

      - name: Upload code coverage
        uses: codecov/codecov-action@v7
        with:
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
        if: matrix.job == 'Tests'

  quality-checks:
    runs-on: ubuntu-24.04
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: Rector + Code style
            commandName: Run Rector + code style check
            command: vendor/bin/rector --ansi --dry-run && vendor/bin/php-cs-fixer fix --dry-run --ansi --verbose
          - name: Psalm
            commandName: Run Psalm analysis
            command: vendor/bin/psalm --show-info=true

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.5

      - name: Install dependencies
        uses: ramsey/composer-install@v4
        with:
          dependency-versions: highest
          composer-options: --prefer-dist

      - name: ${{ matrix.commandName }}
        run: ${{ matrix.command }}
