name: "Continuous Integration"

on:
  pull_request: null
  push:
    branches:
      - "*.x"
      - "master"
  schedule:
    - cron: "42 3 * * 1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  phpunit-mysql:
    name: ${{ matrix.job }}${{ matrix.name }} (PHP ${{ matrix.php-version }} / MySQL ${{ matrix.mysql-version }})
    runs-on: "ubuntu-24.04"
    strategy:
      matrix:
        php-version:
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
        mysql-version:
          - "8.0"
        dependencies:
          - "highest"
        composer-options: 
          - "--prefer-dist"
        job:
          - Tests
        include:
          - php-version: "8.5"
            mysql-version: "8.4"
          - php-version: "8.5"
            mysql-version: "8.2"
            job: Infection
          - dependencies: "lowest"
            php-version: "8.1"
            mysql-version: "5.7"
            name: Lowest deps

    steps:
      - name: "Checkout"
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 2
          persist-credentials: false

      - name: 'Use CI Docker Compose override configuration'
        run: 'cp docker-compose.ci.override.yml docker-compose.override.yml'

      - name: 'Start MySQL'
        run: 'docker compose up -d mysql'
        env:
          MYSQL_VERSION: "${{ matrix.mysql-version }}"

      - name: "Install PHP"
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "pcov"
          ini-values: "zend.assertions=1"
          extensions: "mysqli, pdo_mysql"
        
      - name: Remove unneeded dependencies
        run: |-
          composer remove --dev --no-update \
            facile-it/facile-coding-standard \
            rector/rector

      - name: Remove Psalm & Infection
        if: matrix.job != 'Infection'
        run: |-
          composer remove --dev --no-update \
            psalm/plugin-phpunit \
            roave/infection-static-analysis-plugin \
            vimeo/psalm

      - name: Install dependencies
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0
        with:
          dependency-versions: ${{ matrix.dependencies }}
          composer-options: ${{ matrix.composer-options }}

      - name: 'Wait for MySQL to be ready'
        run: 'make wait-mysql'
        env:
          MYSQL_VERSION: "${{ matrix.mysql-version }}"

      - name: "Run PHPUnit with coverage"
        run: "vendor/bin/phpunit --coverage-clover=coverage.xml"
        if: matrix.job != 'infection'

      - name: "Run mutation testing with Infection"
        run: "vendor/bin/roave-infection-static-analysis-plugin --ansi --show-mutations"
        if: matrix.job == 'infection'

      - name: Upload code coverage
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
        if: matrix.job == 'Tests'

  quality-checks:
    runs-on: ubuntu-24.04
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: Rector
            commandName: Run Rector
            command: 'vendor/bin/rector --ansi --dry-run'
          - name: Code style
            commandName: Run code style check
            command: 'vendor/bin/php-cs-fixer fix --dry-run --ansi --diff'
          - name: Psalm
            commandName: Run Psalm analysis
            command: vendor/bin/psalm --show-info=true

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 2
          persist-credentials: false

      - name: Install PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: 8.5

      - name: Install dependencies
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0
        with:
          dependency-versions: highest
          composer-options: --prefer-dist

      - name: ${{ matrix.commandName }}
        env:
          COMMAND: ${{ matrix.command }}
        run: $COMMAND
