name: "Continuous Integration"

on:
  pull_request: null
  push:
    branches:
      - "*.x"
      - "master"
  schedule:
    - cron: "42 3 * * 1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  phpunit-mysql:
    name: ${{ matrix.job }}${{ matrix.name }} (PHP ${{ matrix.php-version }} / MySQL ${{ matrix.mysql-version }})
    runs-on: "ubuntu-24.04"

    strategy:
      matrix:
        php-version:
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
        mysql-version:
          - "8.0"
        mysql-image:
          - "mysql@sha256:7dcddc01f13bab2f15cde676d44d01f61fc9f99fe7785e86196dfc07d358ae2b"
        dependencies:
          - "highest"
        composer-options:
          - "--prefer-dist"
        job:
          - Tests
        include:
          - php-version: "8.5"
            mysql-version: "8.0"
            mysql-image: "mysql@sha256:7dcddc01f13bab2f15cde676d44d01f61fc9f99fe7785e86196dfc07d358ae2b"
            composer-options: "--prefer-dist --ignore-platform-req=php+"
          - php-version: "8.2"
            mysql-version: "5.7"
            mysql-image: "mysql@sha256:4bc6bc963e6d8443453676cae56536f4b8156d78bae03c0145cbe47c2aad73bb"
          - php-version: "8.5"
            mysql-version: "8.0"
            job: Infection
          - dependencies: "lowest"
            php-version: "8.1"
            mysql-version: "5.7"
            mysql-image: "mysql@sha256:4bc6bc963e6d8443453676cae56536f4b8156d78bae03c0145cbe47c2aad73bb"
            name: Lowest deps

    services:
      mysql:
        image: ${{ matrix.mysql-image }}
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: "Checkout"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 2
          persist-credentials: false

      - name: "Install PHP"
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # 2.37.1
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "pcov"
          ini-values: "zend.assertions=1"
          extensions: "mysqli, pdo_mysql"

      - name: Remove unneeded dependencies
        run: |-
          composer remove --dev --no-update \
            facile-it/facile-coding-standard

      - name: Remove Psalm & Infection
        if: matrix.job != 'Infection'
        run: |-
          composer remove --dev --no-update \
            psalm/plugin-phpunit \
            roave/infection-static-analysis-plugin \
            vimeo/psalm

      - name: Install dependencies
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0
        with:
          dependency-versions: ${{ matrix.dependencies }}
          composer-options: ${{ matrix.composer-options }}

      - name: "Run PHPUnit with coverage"
        run: "vendor/bin/phpunit -c ci/github/phpunit/phpunit.xml --coverage-clover=coverage.xml"
        if: matrix.job != 'Infection'

      - name: "Run mutation testing with Infection"
        run: "vendor/bin/roave-infection-static-analysis-plugin --ansi --show-mutations"
        if: matrix.job == 'Infection'

      - name: Upload code coverage
        uses: codecov/codecov-action@v7
        with:
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
        if: matrix.job == 'Tests'

  quality-checks:
    runs-on: ubuntu-24.04
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: Rector + Code style
            commandName: Run Rector + code style check
            command: vendor/bin/rector --ansi --dry-run && vendor/bin/php-cs-fixer fix --dry-run --ansi --verbose
          - name: Psalm
            commandName: Run Psalm analysis
            command: vendor/bin/psalm --show-info=true

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 2
          persist-credentials: false

      - name: Install PHP
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # 2.37.1
        with:
          php-version: 8.5

      - name: Install dependencies
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0
        with:
          dependency-versions: highest
          composer-options: --prefer-dist

      - name: ${{ matrix.commandName }}
        env:
          COMMAND: ${{ matrix.command }}
        run: bash -c "$COMMAND"
